config/routes.rb
Rails.application.routes.draw do
  	

	# devise_for :users
    root :to => "home#index"
    get '/signup' => 'home#new'
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
    resources :users do
      collection do
        get :forget_password
        patch :change_password
      end
    end
    resources :home
    resources :transactions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord

	belongs_to :user
end

app/models/transaction.rb
require 'csv'
class Transaction < ApplicationRecord
  belongs_to :user

   def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |transaction|
	      csv << transaction.attributes.values
	    end
	  end
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    mount_uploader :image, ImageUploader

    has_one :bank_account, dependent: :destroy
    has_many :transactions, dependent: :destroy

    after_create :create_bank_account

    def create_bank_account
	    self.build_bank_account(account_no: rand(100000000000..999999999999), account_type: "saving", account_balance: 0).save
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

   def current_user
  	 current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
   end

   def require_user
  	 redirect_to login_path unless current_user.present?
   end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_user

  def index
    
  end

  def edit
  end

  def update
    
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    	redirect_to home_index_path if current_user.present?
    end

  	def create
	    if @user = User.find_by(email: params[:session][:email])
	        if @user && @user.valid_password?(params[:session][:password])
	            @user.update_attributes(sign_in_count: @user.sign_in_count+1)
	  			session[:user_id] = @user.id
	            flash[:notice] = "You have successfully logged In."
	            redirect_to home_index_path
	        else
	       		redirect_to login_path
	          flash[:error] = "Invalid Email or Password"
	        end
	    else
	      redirect_to login_path
	      flash[:error] = "Invalid Email, Please try again."
	    end
	end

	def destroy
	    session[:user_id] = nil
	    flash[:success] = "You have successfully logged out."
	    redirect_to login_path
	end

end

app/controllers/transactions_controller.rb
require 'will_paginate/array'
class TransactionsController < ApplicationController
  before_action :require_user

  def index
  	if current_user.role.eql?("user")
  		@transactions = Transaction.where(user_id: current_user.id).order("created_at desc").paginate(:page => params[:page], :per_page => 10)  
  	else
  		if params[:search].present?
  			@transactions =	User.joins(:bank_account).where(bank_accounts: {account_no: params[:search]}).group(:id).map{|x| x.transactions}.flatten
  			@transactions = @transactions.sort_by{|e| [:created_at]}.reverse.paginate(:page => params[:page], :per_page => 10)
  		else
  			@transactions = Transaction.order("created_at desc").paginate(:page => params[:page], :per_page => 10)
  		end
  	end
  	@transactions = Transaction.where(id: params[:transaction]).order("created_at desc").paginate(:page => params[:page], :per_page => 10) if params[:transaction].class.eql?(Array)
  	respond_to do |format|
	  format.html
	  format.csv { send_data @transactions.to_csv }
	  format.xls { send_data @transactions.to_csv(col_sep: "\t") }
	end
  end

  def new
  end

  def create
  	@transaction = current_user.transactions.create(transaction_params)
  	if params[:transaction][:transaction_type].eql?("credit")
  		@transaction.update(total_balance: current_user.bank_account.try(:account_balance) + params[:transaction][:transaction_amount].to_f, transaction_reference: rand(100000000..999999999))
  	elsif params[:transaction][:transaction_type].eql?("debit")
  		@transaction.update(total_balance: current_user.bank_account.try(:account_balance) -params[:transaction][:transaction_amount].to_f, transaction_reference: rand(100000000..999999999))
  	end
  	current_user.bank_account.update(account_balance: @transaction.total_balance)
  	UserMailer.transaction_confirmation(current_user, @transaction).deliver_now	
  	redirect_to transactions_path, notice: 'Transaction completed Successfully.'
  end

  def edit
  end

  def update
    
  end

  def show
  end

  private
  def find_transaction
    @transaction = Transaction.find_by(id: params[:id])
    redirect_to transactions_path unless @transaction
  end

  def transaction_params
    params.require(:transaction).permit(:transaction_type,:transaction_amount,:transaction_reference,:total_balance)
  end
end

app/controllers/users_controller.rb
require 'will_paginate/array'
class UsersController < ApplicationController
  before_action :require_user, except: [:new, :create]
  before_action :find_user, except: [:new, :create,:index]

  def index
    @users = User.where(role: "user").order("name asc").paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.signup_confirmation(@user).deliver_now
      @user.update_attributes(sign_in_count: @user.sign_in_count+1)
      session[:user_id] = @user.id
      redirect_to home_index_path, notice: "Your account created successfully."
    else
      redirect_to  new_user_path
      flash[:notice]=  @user.errors.full_messages.first
    end
  end

  def edit

  end

  def update
    @user.role = params[:user][:role] if params[:user][:role].present?
    if @user.update_attributes(user_params)
      redirect_to admin_users_path, notice: 'User updated Successfully.'
    else
      flash[:notice] = @user.errors.full_messages.first
      render :edit
    end
  end

  def show
  end

  def destroy
    if @user.destroy
      redirect_to  admin_users_path
      @user.alert(request.ip, request.remote_addr, request.env["HTTP_USER_AGENT"], @user.class)
    else
      redirect_to  admin_users_path
    end
  end

  private
  def find_user
    @user = User.find_by(id: params[:id])
    redirect_to admin_users_path unless @user
  end

  def user_params
    params.require(:user).permit(:email,:name,:password,:password_confirmation,:image,:mobile,:address,:status,:state,:dob)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def options_for_transaction_type_select
	    [["Credit","credit"],["Debit","debit"]]
  	end
end

app/views/home/index.html.erb
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">

  </section>

  <!-- Main content -->
  <section class="content">

   <div class="box box-info">
     <div class="text-right attendee-cent-s form-group">
      <%= link_to "Edit", edit_user_path(id: current_user.id), :class => "btn btn-default btn-green" %>
     </div>
          <!-- /.box-header -->
      <div class="box-body box-profile">
          <div class="profile-box">
          <div class="form-group has-feedback text-center">
            <%= current_user.image.present? ? image_tag(current_user.image.url,:width => 100, :height => 100, :class => 'profile-ab') : image_tag("/1.png",:width => 100, :height => 100, :class => 'profile-ab') %>
          </div>
          <h3 class="profilecurrent_username text-center"><%= current_user.name%></h3>
          <p class="text-muted text-center"><%= current_user.address%></p>

        <div class="profile-inner">
        <% if current_user.role.eql?("user")%>
        	<div class="p-blocks">
              <label class="view-a left-a">Account Number</label>
              <span class="view-a right-a"><%= current_user.bank_account.try(:account_no) %></span>
          </div>
          <div class="p-blocks">
              <label class="view-a left-a">Available Balance</label>
              <span class="view-a right-a"><%= current_user.bank_account.try(:account_balance) %></span>
          </div>
         <%end%>
          <div class="p-blocks">
              <label class="view-a left-a">Name</label>
              <span class="view-a right-a"><%= current_user.name%></span>
          </div>
          <!-- <div class="p-blocks">
              <label class="view-a left-a">Gender</label>
              <span class="view-a right-a"><%#= current_user.email%></span>
          </div> -->
          <div class="p-blocks">
              <label class="view-a left-a">Date of birth</label>
              <span class="view-a right-a"><%= current_user.dob%></span>
          </div>
          <div class="p-blocks">
              <label class="view-a left-a">Email</label>
              <span class="view-a right-a"><%= current_user.email%></span>
          </div>
          <div class="p-blocks">
              <label class="view-a left-a">Mobile</label>
              <span class="view-a right-a"><%= current_user.mobile%></span>
          </div>
          <div class="p-blocks">
              <label class="view-a left-a">Address</label>
              <span class="view-a right-a"><%= current_user.address%></span>
          </div>
      </div>

          </div>
      </div>
    </div>

  </section>
  <!-- /.content -->
</div>
<!-- /.content-wrapper -->

app/views/layouts/_flash.html.erb
<% if flash.present? %>
  <div class="row flash-alerts">
    <div class = 'alert alert-dismissable alert-info'>
      <button type="button" class="close" data-dismiss="alert">×</button>
      <% flash.each do |name, msg| %>
        <%= content_tag :h5, msg %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%#= javascript_include_tag :defaults, "nested_form" %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css">
  <%#= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%#= favicon_link_tag '/favicon.png', :rel => 'shortcut icon' %>

  <!-- <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"> -->

</head>
<%if current_user %>
<body class="hold-transition skin-red sidebar-mini fixed">
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <div class="logo" align="center">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><a href="/home"><img src="/2.jpg" class="user-image ad-log-min" alt="User Image" ></a></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><a href="/home"><img src="/2.jpg" class="user-image ad-log" alt="User Image"></a></span>

    </div>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">

    <a class="sidebar-toggle menu-txt" id="id-sidebar-toggle" role="button" data-toggle="offcanvas" href="#">
    <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
     <ul class="nav navbar-nav">
    <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle menu-txt" data-toggle="dropdown">
            <!-- <img src="/favicon.png" class="user-image" alt="User Image"> -->
            <%= current_user.try(:image).present? ? image_tag(current_user.try(:image).try(:url),:width => 100, :height => 100, :class => 'user-image') : image_tag("/assets/1.png",:width => 100, :height => 100, :class => 'user-image') %>
            <span class="hidden-xs"><%= current_user.name.present? ? current_user.name : "Admin" %></span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <!-- <img src="/1.png" class="img-circle" alt="/1.png"> -->
              <%= current_user.try(:image).present? ? image_tag(current_user.try(:image).try(:url),:width => 100, :height => 100, :class => 'img-circle') : image_tag("/assets/1.png",:width => 100, :height => 100, :class => 'img-circle') %>
              <p>
                <%= current_user.name.present? ? current_user.name : "Admin" %>
                <small>Member since <%= current_user.created_at.strftime("%b, %Y")%> </small>
              </p>
            </li>
            <!-- Menu Body -->
            <!-- <li class="user-body">
              <div class="row">
                <div class="col-xs-4 text-center">
                  <a href="#">Followers</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Sales</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Friends</a>
                </div>
              </div> -->
              <!-- /.row -->
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="/home" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <!-- <a href="/logout" class="btn btn-default btn-flat">Sign out</a> -->
                <%= link_to "Sign out", logout_path,:class=>"btn btn-default btn-flat", method: :delete %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>


  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can bMerchandisee found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <!-- <img src="/favicon.png" class="img-circle" alt="User Image"> -->
          <%= current_user.try(:image).present? ? image_tag(current_user.try(:image).try(:url),:width => 100, :height => 100, :class => 'img-circle') : image_tag("/assets/1.png",:width => 100, :height => 100, :class => 'img-circle') %>
        </div>
        <div class="pull-left info">
          <p> <%= current_user.name.present? ? current_user.name : "Admin" %></p>
          <!-- <a href="#"><i class="fa fa-circle text-success"></i> Online</a> -->
        </div>
      </div>
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        
        <% if current_user.role.eql?("manager")%>
          <li class="treeview">
            <a class="menu-txt" href="/users">
              <i class="fa fa-users"></i>
              <span>Users</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-right pull-right"></i>
              </span>
            </a>
          </li>      
        <%end%>
          <li class="treeview">
            <a class="menu-txt" href="/transactions">
              <i class="fa fa fa-money"></i> <span>Transactions</span>
              <span class="pull-right-container">
                <i class="fa fa-angle-right pull-right"></i>
              </span>
            </a>
          </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>
  </div>

<%end%>
            <%= render :partial => "layouts/flash" %>

            <%= yield %>

<%if current_user%>
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; <%= Time.current.strftime("%Y")%> <a href="https://www.google.com/" class="fans-link">DemoTest</a>.</strong> All rights
    reserved.
  </footer>
<%end%>

<!-- <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script> -->
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->

<!-- <script>
  $.widget.bridge('uibutton', $.ui.button);
</script> -->


</body>
</html>

app/views/transactions/index.html.erb
<div class="content-wrapper">
   <!-- Content Header (Page header) -->
   <section class="content-header">
     <h1> Transactions </h1>
   </section>
   <!-- Main content -->
   <section class="content">
    <div class="box box-info">
      <% if current_user.role.eql?("user")%>
        <div class="text-right attendee-cent-s form-group">
        	<%= link_to "Add Transaction", new_transaction_path, :class => "btn btn-default btn-green" %>
        </div>
      <%else%>
        <%= form_tag transactions_path, method: :get, class:"c_form" do  %>
         <div class="input-group">
           <%=  text_field_tag :search, nil, class:"form-control",placeholder: 'Search Account Number' %>
           <div class="input-group-btn">
             <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
           </div>
         </div>
        <%end%>
      <%end%>
            <p class="transaction-log">
              Download:
              <%= link_to "CSV", transactions_path(format: "csv", transaction: @transactions) %> |
              <%= link_to "Excel", transactions_path(format: "xls", transaction: @transactions) %>
            </p>

           <div class="box-body">
             <table id="example2" class="table table-bordered table-hover">
               <thead>
                 <tr>
           				<th>Date</th>
           				<th>Details</th>
                  <th>Ref No</th>
           				<th>Credit/Debit Amount</th>
           				<th>Balance</th>
           			</tr>
               </thead>
               <% @transactions.each do |trans| %>
           			<% unless trans.eql?(nil) %>
           				<tbody>
           					<tr class="even">
                    <td><%= trans.created_at.localtime.strftime("%d %B, %Y %I:%M %p") %></td>
           						<td style="max-width: 200px;">XXXX<%= current_user.bank_account.account_no.last(4) %>/<%= trans.transaction_type %> </td>
           						<td><%= trans.transaction_reference %></td>

                      <td><%= trans.transaction_amount %></td>

                       <td><%= trans.total_balance %></td>
           						
           					</tr>
           				</tbody>
           			<%end%>
           		<%end%>
           	</table>
           	<%= will_paginate @leagues %>
           </div>
         </div>
   </section>
   <!-- /.content -->
 </div>

app/views/transactions/new.html.erb
<div class="content-wrapper">
   <!-- Content Header (Page header) -->
   <section class="content-header">
     <h1> Transactions </h1>
   </section>
   <!-- Main content -->
   <section class="content">
    <div class="box box-info">
      <!-- /.login-logo -->
       <div class="box-body login-box">
       <div class="login-box-body trans-body">
          <%= form_for :transaction,url: transactions_path,:class=> "form-control" do |f| %>
            <div class="form-group">
              <%= f.select :transaction_type,options_for_transaction_type_select,{prompt: 'Please Select Transaction Type'}, class: "form-control", required: true, placeholder: ""%>
            </div>
             
            <div class="form-group">
              <%= f.number_field :transaction_amount, class: "form-control", required: true, placeholder: "Amonut"%>             
            </div>
                  
          <button class="btn btn-primary btn-block login-btn" type="submit">Submit</button>
        <%end%>
        </div>
        </div>
      <!-- /.login-box-body -->
     </div>
   </section>
   <!-- /.content -->
 </div>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>DemoTest</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

  </head>
  <body class="hold-transition login-page">
    <div class="login-box">
       <div class="login-logo">
        <!-- <a href="/index2.html"><b>Admin</b>LTE</a> -->
       </div>
      <!-- /.login-logo -->
       <div class="login-box-body">
          <%= form_for :user,url: user_path, method: :patch,:class=> "form-control",html: {id: "signin-idenity"} do |f| %>
          <div class="form-group">
              <%= f.text_field :name, class: "form-control", required: true, placeholder: "Name"%>
          </div>
                    <div class="form-group">
                        <%= f.email_field :email, class: "form-control", required: true, placeholder: "Email Address"%>            
                    </div>
              <div class="form-group">
             <%= f.file_field :image, class: "form-control" %>
          </div>

                    <div class="form-group">
              <%= f.text_field :mobile, class: "form-control", required: true, placeholder: "Mobile Number"%>             
          </div>
                    <div class="form-group">
            <%= f.text_field :dob, class: "form-control", required: true, placeholder: "Date of Birth", :id=>'userdatetimepicker1', value: (f.object.dob.to_date.strftime("%d/%m/%Y") rescue "")%>
          </div>
          <div class="form-group">
            <%= f.text_field :address, class: "form-control", placeholder: "Address", required: true%>
          </div>
         

          <button class="btn btn-primary btn-block login-btn" type="submit">Submit</button>
        <%end%>
        <a href="/users/new" class="text-center">Already have account ? Login</a>
        </div>
      <!-- /.login-box-body -->
    </div>
  <!-- /.login-box -->
  </body>
</html>
<script type="text/javascript">
  $(document).ready(function(){
    $('#userdatetimepicker1').datetimepicker({
      format: 'DD/MM/YYYY',
      useCurrent: false,
      maxDate: new Date()
    });
    window.onload = function() {
      var myInput = document.getElementById('userdatetimepicker1');
      myInput.onpaste = function(e) {
        e.preventDefault();
      }
    }
  });
</script>

app/views/users/index.html.erb
<div class="content-wrapper">
   <!-- Content Header (Page header) -->
   <section class="content-header">
     <h1> Users </h1>
   </section>
   <!-- Main content -->
   <section class="content">
    <div class="box box-info">
      
      
           <div class="box-body">
             <table id="example2" class="table table-bordered table-hover">
               <thead>
                 <tr>
           				<th>Account Number</th>
           				<th>Name</th>
                   <th>Email</th>
                   <th>Mobile</th>
                   <!-- <th>Date of birth</th> -->
<!--                   <th>Status</th>
 -->           				<th>Actions</th>
           			</tr>
               </thead>
               <%= "No user found." unless @users.present?%>
               <% @users.each do |user| %>
                 <% unless user.eql?(nil) %>
                   <tbody>
                     <tr class="even">
                       <td><%= user.bank_account.try(:account_no) %></td>
                       <td><%= truncate(user.name, omision: "...", length: 30) %></td>
                       <td><%= truncate(user.email, omision: "...", length: 50)%></td>
                       <td><%= user.mobile%></td>
                       <!-- <td><%#= user.dob.try(:strftime, "%d %B, %Y")%></td> -->
                       
                       <td style="max-width: 350px;">
                          <%if user.status.eql?(1)%>
                           <%= link_to 'Deactivate',user_status_admin_users_path(:id => user.id), method: :post,:class=>"btn btn-default btn-red",:data => { :confirm => "Are you sure to deactivate this user?" }%>
                          <%elsif user.status.eql?(0)%>
                           <%= link_to 'Activate',user_status_admin_users_path(:id => user.id), method: :post,:class=>"btn btn-default btn-green",:data => { :confirm => "Are you sure to activate this user?" }%>
                          <%end%>
                         <a><%= link_to "View", user_path(id: user.id), :class=>"btn btn-default btn-green"%></a>
                         <a><%#= link_to "Edit", edit_user_path(id: user.id), :class=>"btn btn-default btn-green"%></a>
                         <a>
                         <%#= link_to 'Delete'.html_safe,  user_path(user.id), method: :delete,:class=>"btn btn-default btn-red", data: {confirm: 'Are you sure to delete this user?' }%></a>
                        </td>
                     </tr>
                   </tbody>
                 <%end%>
               <%end%>
             </table>
             <%= will_paginate @users %>
           </div>
         </div>
   </section>
   <!-- /.content -->
 </div>
 <div class="modal fade" id="myModal" role="dialog">
     <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <div id ="data_container">
            </div>
          </div>
          <div class="modal-footer">
          </div>
        </div>
     </div>
 </div>
 <script type="text/javascript">
  $(document).ready(function(){
    $(".add-model").click(function(){
      $("#myModal").modal('show');
    });
  });

 </script>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>DemoTest</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

  </head>
  <body class="hold-transition login-page">
    <div class="login-box">
       <div class="login-logo">
        <!-- <a href="/index2.html"><b>Admin</b>LTE</a> -->
       </div>
      <!-- /.login-logo -->
       <div class="login-box-body">
          <%= form_for :user,url: users_path,:class=> "form-control",html: {id: "signin-idenity"} do |f| %>
          <div class="form-group">
              <%= f.text_field :name, class: "form-control", required: true, placeholder: "Name"%>
          </div>
                    <div class="form-group">
                        <%= f.email_field :email, class: "form-control", required: true, placeholder: "Email Address"%>            
                    </div>
              <div class="form-group">
             <%= f.file_field :image, class: "form-control" %>
          </div>

                    <div class="form-group">
              <%= f.text_field :mobile, class: "form-control", required: true, placeholder: "Mobile Number"%>             
          </div>
                    <div class="form-group">
            <%= f.text_field :dob, class: "form-control", required: true, placeholder: "Date of Birth", :id=>'userdatetimepicker1', value: (f.object.dob.to_date.strftime("%d/%m/%Y") rescue "")%>
          </div>
          <div class="form-group">
            <%= f.text_field :address, class: "form-control", placeholder: "Address", required: true%>
          </div>
          <div class="form-group">
            <%= f.password_field :password, class: "form-control", placeholder: "Password", required: true%>
          </div>
          <div class="form-group">
            <%= f.password_field :confirm_password, class: "form-control", placeholder: "Confirm Password", required: true%>
          </div>

          <button class="btn btn-primary btn-block login-btn" type="submit">Submit</button>
        <%end%>
        <a href="/login" class="text-center">Already have account ? Login</a>
        </div>
      <!-- /.login-box-body -->
    </div>
  <!-- /.login-box -->
  </body>
</html>
<script type="text/javascript">
  $(document).ready(function(){
    $('#userdatetimepicker1').datetimepicker({
      format: 'DD/MM/YYYY',
      useCurrent: false,
      maxDate: new Date()
    });
    window.onload = function() {
      var myInput = document.getElementById('userdatetimepicker1');
      myInput.onpaste = function(e) {
        e.preventDefault();
      }
    }
  });
</script>